sudo: required
dist: xenial

language: generic

install:
- sudo apt-add-repository -y ppa:octave/stable
- sudo apt-get update -qq
- sudo apt-get install -qq octave liboctave-dev
- sudo git clone --depth=50 https://github.com/MATPOWER/mptest.git $TRAVIS_BUILD_DIR/mptest
- sudo git clone --depth=50 https://github.com/MATPOWER/matpower.git $TRAVIS_BUILD_DIR/matpower

env:
  global:
    - MPSIM_PATH=$TRAVIS_BUILD_DIR/lib:$TRAVIS_BUILD_DIR/lib/t
    - MPTEST_PATH=$TRAVIS_BUILD_DIR/mptest/lib:$TRAVIS_BUILD_DIR/mptest/lib/t
    - MATPOWER_PATH=$TRAVIS_BUILD_DIR/matpower/lib:$TRAVIS_BUILD_DIR/matpower/lib/t
    - MIPS_PATH=$TRAVIS_BUILD_DIR/matpower/mips/lib:$TRAVIS_BUILD_DIR/matpower/mips/lib/t
    - MOST_PATH=$TRAVIS_BUILD_DIR/matpower/most/lib:$TRAVIS_BUILD_DIR/matpower/most/lib/t
    - SEARCH_PATH_NOMATPOWER=$MPSIM_PATH:$MPTEST_PATH
    - SEARCH_PATH_W_MATPOWER=$MPSIM_PATH:$MPTEST_PATH:$MATPOWER_PATH:$MIPS_PATH:$MOST_PATH

script:
- octave-cli --no-gui -p $SEARCH_PATH_NOMATPOWER --eval ver
- octave-cli --no-gui -p $SEARCH_PATH_NOMATPOWER --eval "test_mpsim(0,1)"
- octave-cli --no-gui -p $SEARCH_PATH_W_MATPOWER --eval mpver
- octave-cli --no-gui -p $SEARCH_PATH_W_MATPOWER --eval "test_mpsim(0,1)"
