sudo: required
dist: xenial

language: generic

install:
- sudo apt-add-repository -y ppa:octave/stable
- sudo apt-get update -qq
- sudo apt-get install -qq octave liboctave-dev
- sudo git clone --depth=50 https://github.com/MATPOWER/mptest.git $TRAVIS_BUILD_DIR/mptest
- sudo git clone --depth=50 https://github.com/MATPOWER/matpower.git $TRAVIS_BUILD_DIR/matpower

env:
  global:
    - MPSIM_PATH=$TRAVIS_BUILD_DIR/lib:$TRAVIS_BUILD_DIR/lib/t
    - MPTEST_PATH=$TRAVIS_BUILD_DIR/mptest/lib:$TRAVIS_BUILD_DIR/mptest/lib/t
    - MATPOWER_PATH=$TRAVIS_BUILD_DIR/matpower
    - SEARCH_PATH=$MPSIM_PATH:$MPTEST_PATH


script:
# test MP-Sim w/o MATPOWER
- octave-cli --no-gui -p $SEARCH_PATH --eval ver
- octave-cli --no-gui -p $SEARCH_PATH --eval "test_mpsim(0,1)"

# install MATPOWER
- octave-cli --no-gui -p $MATPOWER_PATH --eval "install_matpower(1,1,1)"
- octave-cli --no-gui --eval mpver

# test MP-Sim with MATPOWER
- octave-cli --no-gui -p $SEARCH_PATH --eval mpver
- octave-cli --no-gui -p $SEARCH_PATH --eval "test_mpsim(0,1)"
