classdef burger_shop < mpsim
%Subclass of MPSIM.  Specify all simulation definitions here.

%   MP-Sim
%   Copyright (c) 2016, 2017 by Haeyong (David) Shin, Ray Zimmerman
%
%   This file is part of MP-Sim.
%   Covered by the 3-clause BSD License (see LICENSE file for details).

    properties
    end
    methods
        function initialize(sim)
            %% set default values for simulator properties
            sim.l = 1;              %% l, length of simulation time step
            sim.units = 'hours';    %% units of l, length of time step
            sim.T = 6*3*3;          %% T, number of simulation periods per run
            sim.R = 2;              %% R, dimension(s) of simulation runs
            
            %% create and add shared state objects
            sim.add_shared_state(mpsim_shared_x_queue('order_queue'));
            sim.add_shared_state(mpsim_shared_x_numeric('frozen_inventory'));
            sim.add_shared_state(mpsim_shared_x_numeric('thawed_inventory'));
            sim.add_shared_state(mpsim_shared_x_numeric('grilled_inventory'));
            
            %% create and register process objects
            sim.register_process(bg_order(...
                struct( 'name', 'order', ...
                        'f', 6*3, ...
                        't0', 1, ...
                        'tau', 0) ));
            sim.register_process(bg_deliver(...
                struct( 'name', 'deliver', ...
                        'f', 6 , ...
                        't0', 2, ...
                        'tau', 1) ));
            sim.register_process(bg_defrost(...
                struct( 'name', 'defrost', ...
                        'f', 2, ...
                        't0', 1, ...
                        'tau', 1) ));
            sim.register_process(bg_grill(...
                struct( 'name', 'grill', ...
                        'f', 1, ...
                        't0', 1, ...
                        'tau', 0) ));
        end
    end
end
