function y_ps = output(ps, x, u, sim_name, sim_outputdir, r, idx, out_args)
%OUTPUT @bg_grill/output

%   MP-Sim
%   Copyright (c) 2016, 2017 by Haeyong Shin, Ray Zimmerman
%
%   This file is part of MP-Sim.
%   Covered by the 3-clause BSD License (see LICENSE file for details).

if nargin == 1
    y_ps = struct( ...
            'grills', 0, ...
            'sold', 0, ...
            'frozen_inventory', 0, ...
            'thawed_inventory', 0, ...
            'grilled_inventory', 0 ...
        );
else
    y_ps = struct( ...
            'grills', out_args, ...
            'sold', u.sold, ...
            'frozen_inventory', x.shared.frozen_inventory, ...
            'thawed_inventory', x.shared.thawed_inventory, ...
            'grilled_inventory', x.shared.grilled_inventory ...
        );
end
